### ISSUE TITLE
2020-09-14 - KDB Project Call Meeting Agenda

### ISSUE THREAD

**Issue by mcleo-d** [finos/kdb#26]
## Date
Monday, September 14th, 2020 - 10am EST / 3pm BST

_// First Monday of every month_

## Untracked attendees
| Fullname | Affiliation | GitHub Username |
|:-----|:-----|:-----|
| Andy Malakov |  EPAM |  |
| John Burton |  EPAM |  |
| Stuart Farr | EPAM |  |

## Agenda

- (5 min) Convene, roll call, welcome new people.
- (5 min) Approve previous meeting minutes
  - _Approved by acclamation._
- (12 min) @mcleo-d to introduce how Minutes work under GitHub.
  - GitHub Actions behind the scenes.
- (25 min) Introduction to TimeBase as potential FINOS project.
  - https://www.deltixlab.com/products/timebase/
  - Learn about:
    - Language it's implemented in.
      - _GC-free Java for microsecond latencies_
    - How it scales.
    - Code snippets for querying from C++ / Java.
    - Asof join example?
    - Feature engineering?  Z-scores, etc.
      - _create Derived Streams (contrasted with Clean Streams)_
    - Adjustments for corporate actions?
      - _create Derived Streams_
    - Encryption?
      - _Data lives in files.  Delegate to file system._
  - Think about who we can refer as participants in that project.
    - _Engaging existing hedge fund clients?_
- (10 min) Introduction to qclone
  - https://github.com/finos/kdb/tree/master/qclone
- (5 min) AOB, Q&A & Adjourn
  - _Question about Exxeleron qPython._
    - https://github.com/exxeleron/qPython
    - _Community has largely shifted to embedPy / PyQ from Kx Systems_
      - https://code.kx.com/q/ml/embedpy/userguide/
      - https://code.kx.com/q/interfaces/pyq/

### WebEx info
**Webex** 
* https://finos.webex.com/finos/j.php?MTID=mfc9190e818fd85f9e3ece5166f23d920

**Dial-in and Project Materials**
- **US:** +1-415-655-0003 US Toll
- **UK:** +44-20319-88141 UK Toll
- **Access code:** 663 746 304
- **GitHub Repo:** 
  - https://github.com/finos/kdb
- **Wiki Page:** 
  - https://finosfoundation.atlassian.net/wiki/spaces/DT/pages/329383945/kdb+Project

**Comment by mcleo-d** [comment]
Hello

**Comment by maoo** [comment]
hi!

**Comment by mcleo-d** [comment]
Hello 👋

**Comment by alvin-c-shih** [comment]
Howdy!

**Comment by RichardWagener365** [comment]
Hi

**Comment by cm-howard** [comment]
Hello :)

**Comment by adamj-codethink** [comment]
o/

**Comment by mcleo-d** [comment]
Hello 🚶

**Comment by adavies42** [comment]
hi

**Comment by patrickstephens1** [comment]
tada

**Comment by brooklynrob** [comment]
Here

**Comment by avavilau** [comment]
Hi!

**Comment by avavilau** [comment]
# Please visit https://timebase.info/
