### ISSUE TITLE
FINOS and KDB to update KDB `master` branch to `main`

### ISSUE THREAD

**Issue by mcleo-d** [finos/kdb#65]
## Description
The KDB team would like FINOS to coordinate and implement the KDB repo `master` branch to `main` prior to the next KDB project meeting on Monday 14th February 2022. 

### Items
- [x] FINOS to propose branch name change date to KDB project team.
- [x] KDB to confirm the project has committed and merged outstanding pull requests prior to change.
- [x] FINOS to implement branch change.
- [ ] KDB project to implement branch remapping as documented by Compliant Financial Infrastructure 
  - https://github.com/finos/compliant-financial-infrastructure/issues/119#issuecomment-843231539
- [ ] FINOS and KDB to feedback progress at KDB project meeting on Monday 14th February 2022.

**Comment by TheJuanAndOnly99** [comment]
Hey @alvin-c-shih we can take care of the branch name change on Wednesday the 19th of January. Does that give you enough time to commit and merge outstanding pull requests?

**Comment by alvin-c-shih** [comment]
Yes, the 19th sounds good.

Note that there are three repositories related to the FINOS kdb Project:
- https://github.com/finos/kdb
- https://github.com/finos/kdb-studio
- https://github.com/finos/qPython

Thanks!

**Comment by TheJuanAndOnly99** [comment]
Hi @alvin-c-shih I will procede with the branch name changes tomorrow, January 19th. Are the repos ready?

**Comment by alvin-c-shih** [comment]
No pending PRs on any of the three projects.
So good to go!
Thanks!

**Comment by TheJuanAndOnly99** [comment]
Done! @mcleo-d @alvin-c-shih 

The master branches for these repositories have been renamed to main:

- https://github.com/finos/kdb
- https://github.com/finos/kdb-studio
- https://github.com/finos/qPython 

Your members will have to manually update their local environments. GitHub will let them know when they visit the repository, or you can share the following commands.
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by mcleo-d** [comment]
Thank you @TheJuanAndOnly99 - That's awesome 👏🏻  💯 💯 💯 

@alvin-c-shih - Are you able to take the testing forward with the team?

**Comment by TheJuanAndOnly99** [comment]
@alvin-c-shih @mcleo-d thanks for pushing the adoption of inclusive language! Closing this.
