### ISSUE TITLE
WhiteSource Integration for KDB Repo

### ISSUE THREAD

**Issue by mcleo-d** [finos/kdb#72]
## Description

This GitHub issue is a request to the FINOS Infrastructure team to work with @alvin-c-shih and the FINOS KDB project to integrate WhiteSource on the FINOS [kdb](https://github.com/finos/kdb) repo. 

https://community.finos.org/docs/development-infrastructure/code-validation/whitesource

## Actions
- [ ] WhiteSource integrated into [kdb](https://github.com/finos/kdb) repo.
- [ ] FINOS works with KDB team on exclusions and false positive filtering.
- [ ] WhiteSource rolled out for kdb.

cc @maoo @TheJuanAndOnly99 @robmoffat

**Comment by gyorokpeter** [comment]
This project probably doesn't apply, as it has no dependencies, nor a _way_ to specify dependencies.

**Comment by maoo** [comment]
> This project probably doesn't apply, as it has no dependencies, nor a _way_ to specify dependencies.

Thanks @gyorokpeter , in this case I'll close this issue.
